version: '3.8'

services:
  api-java-core:
    build: .
    container_name: container-api-bff
    ports:
      - "8086:8086"  # Mapeia a porta 8086 do host para a porta 8086 do container
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # Ativa o perfil de produção
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
