version: "3.8"

services:
  api:
    build: .
    container_name: produto-fabricante-bff
    ports:
      - "8086:8086"
    command: ["java", "-jar", "app.jar"]
    restart: always

    extra_hosts:
      - host.docker.internal:host-gateway